### ISSUE TITLE
Update code compatability with Nim v0.20.0

### ISSUE THREAD

**Issue by theAkito** [lihf8515/parseini#1]
Greetings, thank you for the great module.

```
/home/akito/.nimble/pkgs/parseini-0.1.0/parseini.nim(582) loadConfig
/home/akito/.nimble/pkgs/parseini-0.1.0/parseini.nim(551) loadConfig
/home/akito/.nimble/pkgs/parseini-0.1.0/parseini.nim(463) next
/home/akito/.choosenim/toolchains/nim-0.20.0/lib/system/assign.nim(243) FieldDiscriminantCheck
/home/akito/.choosenim/toolchains/nim-0.20.0/lib/system/fatal.nim(39) sysFatal
Error: unhandled exception: assignment to discriminant changes object branch; compile with -d:nimOldCaseObjects for a transition period [FieldError]
Error: execution of an external program failed:
```

I got this error after upgrading to Nim v0.20.0, because _case object branch transitions via system.reset are deprecated_, which is mentioned [here](https://nim-lang.org/blog/2019/06/06/version-0200-released.html).

I hope there will be a fix available for this. 
Thank you again, good job on the module.

**Comment by lihf8515** [comment]
I have fixed this problem. Please try again.
I am deeply grateful for your discovery.

**Comment by theAkito** [comment]
> 
> 
> I have fixed this problem. Please try again.
> I am deeply grateful for your discovery.

Great job! It works! Thank you very much for the quick fix. :)
